server:
  port: 5555
  servlet:
    context-path:
spring:
  application:
    name: cyber-done-device-microservice
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/device-microservice-db
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLInnoDBDialect
security:
  aes-key: -1, -2, -3, 100, 100, -88, 100, -95, 100, -69, 95, 48, 77, -78, 100, 62
  jwt-secret: d2980f58-3d82-4144-b802-406f4b47930b-5784cca4-0b50-425e-ac6c-bd651e0c788d
  jwt-expiration-time-ms: 86400000 #24 hours 86400000
mqtt:
  username: user
  password: Qwerty123
  clean-session: false
  connection-timeout: 10
  auto-reconnect: true
  max-in-flight-messages: 100
  client:
    name: CyberDoneDeviceMicroservice
    url: tcp://192.168.1.100:1883
    quality-of-service: 2